environment:
  language: dockercompose
  vars:
    DOCKER_TAG: $DOTCI_SHA

build:
  before:
    - 'for file in `find Dockerfile Gemfile Gemfile.lock -type f -not -path "./.git/*"`; do touch -d "\$(git rev-list -n 1 HEAD \$file | xargs git show -s --format=%ai)" \$file; done'
    - echo $DOTCI_SHA > REVISION
    - 'touch -d "\$(git rev-list -n 1 HEAD | xargs git show -s --format=%ai)" REVISION'

plugins:
  <% if( DOTCI_BRANCH =~ /^deploy_request.*/) { %>
  - request_deploy
  <% } else if( DOTCI_BRANCH =~ /^deploy_bot_uat.*/ || DOTCI_BRANCH == 'master' ) { %>
  - request_deploy:
      deploy_bot:
        colo: uat
  <% } else if( DOTCI_BRANCH =~ /^deploy_bot_staging.*/) { %>
  - request_deploy:
      deploy_bot:
        colo: staging
  <% } else if (DOTCI_TAG =~ /v?[0-9]+\.[0-9]+\.[0-9]+.*/ ) { %>
  - request_deploy:
      deploy_bot:
        manual: true
        colo: production
  <% } %>