defaults: &defaults
  deployment_repo: git@github.groupondev.com:gurus/groupon_gurus
  deployment_setup: >
    bundle install
    --without development test
    --path .bundle

uat:
  <<: *defaults
  deployment_command: >
    REVISION=GIT_SHA_TO_DEPLOY
    bundle exec cap uat docker:deploy --trace

staging:
  <<: *defaults
  deployment_command: >
    REVISION=GIT_SHA_TO_DEPLOY
    bundle exec cap staging docker:deploy

production:
  <<: *defaults
  deployment_command: >
    REVISION=GIT_SHA_TO_DEPLOY
    bundle exec cap production docker:deploy