defaults: &defaults
  adapter: postgresql
  encoding: utf8
  reconnect: true
  pool: 5
  wait_timeout: 50
  # max time to wait for a db connection, in ms
  connect_timeout: 50
  # read/write timeouts in ms
  read_timeout: 1000
  write_timeout: 1000
  prepared_statements: false
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *defaults

staging:
  <<: *defaults

uat:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
